export const KEY_LABEL_MAP: Record<string, string> = {
  candidate_age: "Edad del candidato",
  candidate_avature_id: "ID Avature del candidato",
  candidate_category: "Categoría del candidato",
  candidate_city: "Ciudad del candidato",
  candidate_country: "País del candidato",
  candidate_created_at: "Fecha de creación del candidato",
  candidate_current_job_title: "Puesto actual del candidato",
  candidate_cv: "CV del candidato",
  candidate_date_of_birth: "Fecha de nacimiento del candidato",
  candidate_email: "Email del candidato",
  candidate_first_name: "Nombre del candidato",
  candidate_id: "ID del candidato",
  candidate_job_stage_candidate: "Candidato (Job Stage)",
  candidate_job_stage_created_at: "Creado en (Job Stage)",
  candidate_job_stage_current_stage: "Etapa actual (Job Stage)",
  candidate_job_stage_id: "ID (Job Stage)",
  candidate_job_stage_job: "Job (Job Stage)",
  candidate_job_stage_recruiter: "Recruiter (Job Stage)",
  candidate_job_stage_updated_at: "Actualizado en (Job Stage)",
  candidate_last_name: "Apellido del candidato",
  candidate_latest_update_linkedin:
    "Última actualización de LinkedIn del candidato",
  candidate_linkedin: "LinkedIn del candidato",
  candidate_location: "Ubicación del candidato",
  candidate_name: "Nombre completo del candidato",
  candidate_other_url: "Otra URL del candidato",
  candidate_phone_extract: "Teléfono extraído del candidato",
  candidate_phone_number: "Teléfono del candidato",
  candidate_previous_job_title: "Puesto anterior del candidato",
  candidate_recruiter: "Recruiter del candidato",
  candidate_second_email: "Segundo email del candidato",
  candidate_show_technical_resume: "Mostrar CV técnico del candidato",
  candidate_stage_candidate: "Candidato (Stage)",
  candidate_stage_created_at: "Creado en (Stage)",
  candidate_stage_id: "ID (Stage)",
  candidate_stage_job: "Job (Stage)",
  candidate_stage_recruiter: "Recruiter (Stage)",
  candidate_stage_scoreboard: "Scoreboard (Stage)",
  candidate_stage_stage: "Etapa (Stage)",
  candidate_stage_updated_at: "Actualizado en (Stage)",
  candidate_state_province: "Estado/Provincia del candidato",
  candidate_tech: "Tecnologías del candidato",
  candidate_technical_resume: "CV técnico del candidato",
  candidate_updated_at: "Última actualización del candidato",
  candidate_uuid: "UUID del candidato",
  candidate_years_in_last_job: "Años en último trabajo del candidato",
  candidatecustom_dni: "DNI del candidato",
  candidatecustom_opciones_desplegables: "Opciones desplegables del candidato",
  candidatecustom_opciones_simples: "Opciones simples del candidato",
  company_created_at: "Fecha de creación de la empresa",
  company_description: "Descripción de la empresa",
  company_direction: "Dirección de la empresa",
  company_email: "Email de la empresa",
  company_id: "ID de la empresa",
  company_name: "Nombre de la empresa",
  company_owner_phone: "Teléfono del dueño de la empresa",
  company_perks: "Beneficios de la empresa",
  company_phone_number: "Teléfono de la empresa",
  company_updated_at: "Última actualización de la empresa",
  company_uuid: "UUID de la empresa",
  current_stage_name: "Nombre de la etapa actual",
  interview_day: "Día de la entrevista",
  interview_day_number: "Número de día de la entrevista",
  interview_hour: "Hora de la entrevista",
  interview_minutes: "Minutos de la entrevista",
  job_category: "Categoría del puesto",
  job_company: "Empresa del puesto",
  job_created_at: "Fecha de creación del puesto",
  job_currency: "Moneda del puesto",
  job_description: "Descripción del puesto",
  job_english_level: "Nivel de inglés del puesto",
  job_exclusive: "Puesto exclusivo",
  job_id: "ID del puesto",
  job_is_open: "Puesto abierto",
  job_is_public: "Puesto público",
  job_job_perks: "Beneficios del puesto",
  job_location: "Ubicación del puesto",
  job_modality: "Modalidad del puesto",
  job_place_id: "ID de ubicación del puesto",
  job_place_of_work: "Lugar de trabajo",
  job_positions: "Número de posiciones",
  job_priority: "Prioridad del puesto",
  job_public_description: "Descripción pública del puesto",
  job_public_scoreboard_template: "Template de scoreboard público del puesto",
  job_public_title: "Título público del puesto",
  job_questions: "Preguntas del puesto",
  job_salary_expected: "Salario esperado del puesto",
  job_salary_max: "Salario máximo del puesto",
  job_salary_min: "Salario mínimo del puesto",
  job_stage_template_set: "Set de templates de etapas del puesto",
  job_tech: "Tecnologías del puesto",
  job_technical_info: "Información técnica del puesto",
  job_technical_requirements: "Requisitos técnicos del puesto",
  job_timezone: "Zona horaria del puesto",
  job_title: "Título del puesto",
  job_updated_at: "Última actualización del puesto",
  job_visible_id: "ID visible del puesto",
  jobcustom_campo_requerido_prueba_fecha: "Campo requerido prueba (Fecha)",
  jobcustom_dato_requerido_de_prueba: "Dato requerido de prueba",
  recruiter_consulting_firm: "Consultora del recruiter",
  recruiter_cookie: "Cookie del recruiter",
  recruiter_created_at: "Fecha de creación del recruiter",
  recruiter_email: "Email del recruiter",
  recruiter_id: "ID del recruiter",
  recruiter_is_active: "Recruiter activo",
  recruiter_is_admin: "Recruiter administrador",
  recruiter_is_external: "Recruiter externo",
  recruiter_last_name: "Apellido del recruiter",
  recruiter_linkedin: "LinkedIn del recruiter",
  recruiter_name: "Nombre del recruiter",
  recruiter_updated_at: "Última actualización del recruiter",
  stage_created_at: "Fecha de creación de la etapa",
  stage_description: "Descripción de la etapa",
  stage_id: "ID de la etapa",
  stage_job: "Job de la etapa",
  stage_name: "Nombre de la etapa",
  stage_order: "Orden de la etapa",
  stage_status_options: "Opciones de estado de la etapa",
  stage_template: "Template de la etapa",
  stage_updated_at: "Última actualización de la etapa",
};
