export const KEY_LABEL_MAP_EN: Record<string, string> = {
  candidate_age: "Candidate age",
  candidate_avature_id: "Candidate Avature ID",
  candidate_category: "Candidate category",
  candidate_city: "Candidate city",
  candidate_country: "Candidate country",
  candidate_created_at: "Candidate creation date",
  candidate_current_job_title: "Candidate current job title",
  candidate_cv: "Candidate CV",
  candidate_date_of_birth: "Candidate date of birth",
  candidate_email: "Candidate email",
  candidate_first_name: "Candidate first name",
  candidate_experience: "Candidate experience",
  candidate_id: "Candidate ID",
  candidate_job_stage_candidate: "Candidate (Job Stage)",
  candidate_job_stage_created_at: "Created at (Job Stage)",
  candidate_job_stage_current_stage: "Current stage (Job Stage)",
  candidate_job_stage_id: "ID (Job Stage)",
  candidate_job_stage_job: "Job (Job Stage)",
  candidate_job_stage_recruiter: "Recruiter (Job Stage)",
  candidate_job_stage_updated_at: "Updated at (Job Stage)",
  candidate_last_name: "Candidate last name",
  candidate_latest_update_linkedin: "Candidate latest LinkedIn update",
  candidate_linkedin: "Candidate LinkedIn",
  candidate_location: "Candidate location",
  candidate_name: "Candidate full name",
  candidate_other_url: "Candidate other URL",
  candidate_phone_extract: "Candidate extracted phone",
  candidate_phone_number: "Candidate phone number",
  candidate_previous_job_title: "Candidate previous job title",
  candidate_recruiter: "Candidate recruiter",
  candidate_second_email: "Candidate secondary email",
  candidate_show_technical_resume: "Show candidate technical CV",
  candidate_stage_candidate: "Candidate (Stage)",
  candidate_stage_created_at: "Created at (Stage)",
  candidate_stage_id: "ID (Stage)",
  candidate_stage_job: "Job (Stage)",
  candidate_stage_recruiter: "Recruiter (Stage)",
  candidate_stage_scoreboard: "Scoreboard (Stage)",
  candidate_stage_stage: "Stage (Stage)",
  candidate_stage_updated_at: "Updated at (Stage)",
  candidate_state_province: "Candidate state/province",
  candidate_tech: "Candidate technologies",
  candidate_technical_resume: "Candidate technical CV",
  candidate_updated_at: "Candidate last update",
  candidate_uuid: "Candidate UUID",
  candidate_years_in_last_job: "Candidate years in last job",
  candidatecustom_dni: "Candidate DNI",
  candidatecustom_opciones_desplegables: "Candidate dropdown options",
  candidatecustom_opciones_simples: "Candidate simple options",
  company_created_at: "Company creation date",
  company_description: "Company description",
  company_direction: "Company address",
  company_email: "Company email",
  company_id: "Company ID",
  company_name: "Company name",
  company_owner_phone: "Company owner's phone",
  company_perks: "Company perks",
  company_phone_number: "Company phone number",
  company_updated_at: "Company last update",
  company_uuid: "Company UUID",
  current_stage_name: "Current stage name",
  interview_day: "Interview day",
  interview_day_number: "Interview day number",
  interview_hour: "Interview hour",
  interview_minutes: "Interview minutes",
  job_category: "Job category",
  job_company: "Job company",
  job_created_at: "Job creation date",
  job_currency: "Job currency",
  job_description: "Job description",
  job_english_level: "Job English level",
  job_exclusive: "Exclusive job",
  job_id: "Job ID",
  job_is_open: "Job is open",
  job_is_public: "Job is public",
  job_job_perks: "Job perks",
  job_location: "Job location",
  job_modality: "Job modality",
  job_place_id: "Job place ID",
  job_place_of_work: "Place of work",
  job_positions: "Number of positions",
  job_priority: "Job priority",
  job_public_description: "Public job description",
  job_public_scoreboard_template: "Job public scoreboard template",
  job_public_title: "Public job title",
  job_questions: "Job questions",
  job_salary_expected: "Expected job salary",
  job_salary_max: "Maximum job salary",
  job_salary_min: "Minimum job salary",
  job_stage_template_set: "Job stage template set",
  job_tech: "Job technologies",
  job_technical_info: "Job technical info",
  job_technical_requirements: "Job technical requirements",
  job_timezone: "Job timezone",
  job_title: "Job title",
  job_updated_at: "Job last update",
  job_visible_id: "Job visible ID",
  jobcustom_campo_requerido_prueba_fecha: "Required test field (Date)",
  jobcustom_dato_requerido_de_prueba: "Required test data",
  recruiter_consulting_firm: "Recruiter's consulting firm",
  recruiter_cookie: "Recruiter cookie",
  recruiter_created_at: "Recruiter creation date",
  recruiter_email: "Recruiter email",
  recruiter_id: "Recruiter ID",
  recruiter_is_active: "Recruiter is active",
  recruiter_is_admin: "Recruiter is admin",
  recruiter_is_external: "Recruiter is external",
  recruiter_last_name: "Recruiter last name",
  recruiter_linkedin: "Recruiter LinkedIn",
  recruiter_name: "Recruiter name",
  recruiter_updated_at: "Recruiter last update",
  stage_created_at: "Stage creation date",
  stage_description: "Stage description",
  stage_id: "Stage ID",
  stage_job: "Stage job",
  stage_name: "Stage name",
  stage_order: "Stage order",
  stage_status_options: "Stage status options",
  stage_template: "Stage template",
  stage_updated_at: "Stage last update",
};
